name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install FontTools AFDKO
      
    - name: remove numbers and #*
      run: |
        rm svg/u0023.svg svg/u002a.svg 
        rm svg/u003*.svg
        cd svg/
        for i in $(ls u003*_20e3.svg); do
          cp $i $(echo $si | sed -E 's/(u003\d_)(20e3.svg)/\1fe0f_\2/g')
          done
        cd ..
        
    - name: Build Font
      run: |
        python3 make_bw_font.py -o fonts -r 2.101 --gsub GSUB.fea --gpos GPOS.fea --uvs UVS.txt svg_bw flags_bw
        python3 make_svg_font.py -z -r 2.101 svg flags fonts/NotoEmoji.otf -v
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          if-no-files-found: error
          path: |
            ./fonts/*.otf
