name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install FontTools AFDKO
      
    - name: remove numbers and #*
      run: |
        rm svg/u0023.svg svg/u002a.svg 
        rm svg/u003*.svg
        
    - name: Build Font
      run: |
        python3 make_bw_font.py -o fonts -r 2.101 --gsub GSUB.fea --gpos GPOS.fea --uvs UVS.txt svg_bw flags_bw
        python3 make_svg_font.py -z -r 2.101 svg flags fonts/NotoEmoji.otf -v
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          if-no-files-found: error
          path: |
            ./fonts/*.otf
